### PR TITLE
Preview/19 mfd histograms

### PR DESCRIPTION
**Pull request by chrisbc**
closing #19 we have two views accessible at the routes:

 - /PreviewMFD ( a histogram view)
 - /PreviewLineMFD ( a line view, similar to the opensha PNGs)

### CODE REVIEW

**Comment by chrisbc** [comment]
@wooneh looks like I must fix those TS warnings because CI is more picky than me :)

`Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.`

**Comment by chrisbc** [comment]
@wooneh I finally got a config that passes CI with the new d3 dependency. Jest tests will need some attention as d3 needs some transforms setup ( I think ) but this only affect the App test which I've disabled.

**Review by wooneh — APPROVED** [review]
The graphs look very nice! Is there a reason for using d3 directly instead of charting libraries that build off it e.g. visx?

**Comment by chrisbc** [comment]
> The graphs look very nice! Is there a reason for using d3 directly instead of charting libraries that build off it e.g. visx?

Not really - just that  I've more experience using D3 directly.  But maybe it would bee easier to maintain & quicker doing the other. This is just a preview, so we can review this again. Thanks!

**Pull request merged**
