### PR TITLE
Added heatmap

### PR DESCRIPTION
**Pull request by wooneh**
Added heatmap to hazard data

image

Currently it uses the default gradient from https://github.com/OpenGov/react-leaflet-heatmap-layer#api, we can tweak that to reflect how we want the data presented.

### CODE REVIEW

**Review by chrisbc — CHANGES_REQUESTED** [review]
Hi @wooneh this looks pretty good but when zooming the heatmap colours are not consistent -  'hot' points cool down as you zoom in. I tried messing with some arguments myself but nothing simple seemed to impact it. It may be a bug in the library we're using, rather than the way we're using it.

**Comment by wooneh** [comment]
> Hi @wooneh this looks pretty good but when zooming the heatmap colours are not consistent - 'hot' points cool down as you zoom in. I tried messing with some arguments myself but nothing simple seemed to impact it. It may be a bug in the library we're using, rather than the way we're using it.

When zooming in the points get "diluted" since the point density is lower. When zoomed out the data points are a lot closer together (relatively) so the heat increases.

Some things we could try:
* Increase the point radius when zoomed in. We would want to base this on zoom level since a larger radius would increase the point density a lot more when zoomed out. Just need to find a balance...
* Increase the opacity will help increasing visibility of lighter points when zoomed in
* Decrease blur for more well-defined points
* Is the current gradient good? `{ 0.4: 'blue', 0.8: 'orange', 1.0: 'red' }`

Let me know what you think and any other suggestions we could try.

**Comment by chrisbc** [comment]
> When zooming in the points get "diluted" since the point density is lower.

@wooneh hmmm,  so we need to either change this behaviour or find another control. 

I tried the others things you suggested:  opacity, blur, and  the gradient too, even tweaking the intensity fn, but nothing helped with the basic issue. We need the colour scale to be meaningful and stable  - it shouldn't be affected so much by zoom level.

If you look at the http://leaflet.github.io/Leaflet.heat/demo/ - that behaves how we want.  There is some colour merging due to overlap & blur etc at low zoom, but the colour temp of the hot areas stays consistent as the zoom increases.

**Comment by wooneh** [comment]
> > When zooming in the points get "diluted" since the point density is lower.
> 
> @wooneh hmmm, so we need to either change this behaviour or find another control.
> 
> I tried the others things you suggested: opacity, blur, and the gradient too, even tweaking the intensity fn, but nothing helped with the basic issue. We need the colour scale to be meaningful and stable - it shouldn't be affected so much by zoom level.
> 
> If you look at the http://leaflet.github.io/Leaflet.heat/demo/ - that behaves how we want. There is some colour merging due to overlap & blur etc at low zoom, but the colour temp of the hot areas stays consistent as the zoom increases.

Thanks for the example! Will try to replicate this behaviour, just needs a bit of tweaking.

**Comment by chrisbc** [comment]
@wooneh you'll need to rebase from deploy-test following my merge of #61

**Comment by wooneh** [comment]
@chrisbc I've modified the parameters to vary with zoom level so as to retain heat
 The radius is computed with a linear mapping between a specified zoom range and radius.
 e.g. Between zoom 6 and 10, the radius increases through a linear mapping. We also vary the max intensity, which determines how the map views a point as "hot".

Examples:
image
image
image

**Comment by chrisbc** [comment]
HI @wooneh this is working much better now, bu I'm going to close the PR unmerged because I don't wont to move the feature in as-is,   I have found another vizualisation which will be more useful than heatmap. It requires a bit more API support, but I'll put together a sample file and raise a ticket to create a new preview for this.

**Comment by chrisbc** [comment]
Parking this branch as mentioned above. Look for new geojson hazard contour plot feature as its  potential replacement.

**Pull request closed without merging**
